export const ERROR_CODES = {

  INVALID_API_KEY:
    "INVALID_API_KEY",

  EVENT_NOT_FOUND:
    "EVENT_NOT_FOUND",

  TENANT_NOT_FOUND:
    "TENANT_NOT_FOUND",

  VALIDATION_ERROR:
    "VALIDATION_ERROR",

  INTERNAL_SERVER_ERROR:
    "INTERNAL_SERVER_ERROR"

};