import { PostgresTenantRepository } from "../adapters/postgres/PostgresTenantRepository.js";
import { PostgresEventRepository } from "../adapters/postgres/PostgresEventRepository.js";
import { PostgresAuditRepository } from "../adapters/postgres/PostgresAuditRepository.js";
import { PostgresUsageRepository } from "../adapters/postgres/PostgresUsageRepository.js";
import { PostgresSubscriptionRepository } from "../adapters/postgres/PostgresSubscriptionRepository.js";
import { PostgresBillingRepository } from "../adapters/postgres/PostgresBillingRepository.js";
import { PostgresInvoiceRepository } from "../adapters/postgres/PostgresInvoiceRepository.js";
import { PostgresAdminAuditRepository } from "../adapters/postgres/PostgresAdminAuditRepository.js"
import { PostgresApiKeyRepository } from "../adapters/postgres/PostgresApiKeyRepository.js";
import { PostgresTenantConfigRepository } from "../adapters/postgres/PostgresTenantConfigRepository.js";
import { PostgresTenantUserRepository } from "../adapters/postgres/PostgresTenantUserRepository.js";

export const tenantRepository = new PostgresTenantRepository();
export const eventRepository = new PostgresEventRepository();
export const auditRepository = new PostgresAuditRepository();
export const adminAuditRepository = new PostgresAdminAuditRepository();
export const usageRepository = new PostgresUsageRepository();
export const subscriptionRepository = new PostgresSubscriptionRepository();
export const billingRepository = new PostgresBillingRepository();
export const invoiceRepository = new PostgresInvoiceRepository();
export const apiKeyRepository = new PostgresApiKeyRepository();
export const tenantConfigRepository = new PostgresTenantConfigRepository();
export const tenantUserRepository = new PostgresTenantUserRepository();
